project:
  type: website

title: "Hannah C. Klauber"
site:
  output-dir: "_site"
  render:
    - "*"
  navbar:
    - text: "About"
      href: about.qmd
    - text: "Research"
      href: research.qmd
    - text: "Talks"
      href: talks.qmd
    - text: "CV"
      href: cv.qmd
format:
  html:
    theme: none
    css: styles.css
website:
  title: "Hannah Klauber"
  site-url: "https://hannahklauber.github.io"
  page-footer: |
    <footer class="footer">
      <div class="footer-container">
        <div class="footer-item">
          <h3>Contact</h3>
          <ul class="contact-list">
            <li><a href="mailto:your.email@example.com"><i class="fas fa-envelope"></i> Email</a></li>
             <hr>
            <li><a href="https://www.linkedin.com/in/your-profile" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
            <li><a href="https://github.com/hannahklauber" target="_blank"><i class="fab fa-github"></i> GitHub</a></li>
            <li><a href="https://scholar.google.com/citations?user=your_google_scholar_id" target="_blank"><i class="ai ai-google-scholar"></i> Google Scholar</a></li>
          </ul>
        </div>
        <div class="footer-item">
          <p>© 2024 Hannah C. Klauber. All rights reserved.</p>
        </div>
      </div>
    </footer>
header-includes:
  - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.2/css/academicons.min.css">
